from enum import Enum


class ComplaintStatus(str, Enum):
    REPORTED = "REPORTED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_CITIZEN = "WAITING_FOR_CITIZEN"
    ESCALATION_PENDING = "ESCALATION_PENDING"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ComplaintCategory(str, Enum):
    ROADS = "ROADS"
    WATER_DRAINAGE = "WATER_DRAINAGE"
    SANITATION = "SANITATION"
    ELECTRICAL_INFRASTRUCTURE = "ELECTRICAL_INFRASTRUCTURE"
    PUBLIC_SAFETY = "PUBLIC_SAFETY"
    GENERAL_SERVICES = "GENERAL_SERVICES"
    UNKNOWN = "UNKNOWN"


class EventType(str, Enum):
    COMPLAINT_CREATED = "COMPLAINT_CREATED"
    COMPLAINT_SUBMITTED = "COMPLAINT_SUBMITTED"
    COMPLAINT_ROUTED = "COMPLAINT_ROUTED"
    COMPLAINT_ACKNOWLEDGED = "COMPLAINT_ACKNOWLEDGED"
    COMPLAINT_ASSIGNED = "COMPLAINT_ASSIGNED"
    STATUS_CHANGED = "STATUS_CHANGED"
    COMMITMENT_CREATED = "COMMITMENT_CREATED"
    COMMITMENT_MISSED = "COMMITMENT_MISSED"
    COMMITMENT_FULFILLED = "COMMITMENT_FULFILLED"
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    EXTERNAL_ACTION_STARTED = "EXTERNAL_ACTION_STARTED"
    EXTERNAL_ACTION_SUCCEEDED = "EXTERNAL_ACTION_SUCCEEDED"
    EXTERNAL_ACTION_FAILED = "EXTERNAL_ACTION_FAILED"
    COMPLAINT_RESOLVED = "COMPLAINT_RESOLVED"
    COMPLAINT_CLOSED = "COMPLAINT_CLOSED"


class RecommendationType(str, Enum):
    REQUEST_INFORMATION = "REQUEST_INFORMATION"
    FOLLOW_UP = "FOLLOW_UP"
    VERIFY_COMMITMENT = "VERIFY_COMMITMENT"
    ESCALATE = "ESCALATE"
    LINK_RECURRING = "LINK_RECURRING"


class RecommendationStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"


class CommitmentStatus(str, Enum):
    PENDING = "PENDING"
    FULFILLED = "FULFILLED"
    MISSED = "MISSED"
    CANCELLED = "CANCELLED"
